name: stec_alerta
description: "Aplicación de notificaciones para operadores."
publish_to: 'none'

version: 2.1.6+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  http: ^1.3.0
  path_provider: ^2.1.5
  webview_flutter: ^4.2.0
  webview_flutter_android: ^4.3.3
  shared_preferences: ^2.5.2
  pretty_qr_code: ^3.3.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  package_info_plus: ^8.3.0
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/
