// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjg7n866JYCG-jxCV8nxeodzdlXiXStKs',
    appId: '1:133178926474:web:82906ee593e04bc6f35473',
    messagingSenderId: '133178926474',
    projectId: 'flutter-push-c35bc',
    authDomain: 'flutter-push-c35bc.firebaseapp.com',
    storageBucket: 'flutter-push-c35bc.firebasestorage.app',
    measurementId: 'G-6L8EBCTEYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq6FXZCAC6gCy8qxKmO_ct5_oRyUCmHQw',
    appId: '1:133178926474:android:74c214a39144329af35473',
    messagingSenderId: '133178926474',
    projectId: 'flutter-push-c35bc',
    storageBucket: 'flutter-push-c35bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABEM4MZNjypWBIaPFIjBDvrAz9ZBK_wMs',
    appId: '1:133178926474:ios:28d9c66882cc3f9af35473',
    messagingSenderId: '133178926474',
    projectId: 'flutter-push-c35bc',
    storageBucket: 'flutter-push-c35bc.firebasestorage.app',
    iosBundleId: 'com.example.stecNotifica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABEM4MZNjypWBIaPFIjBDvrAz9ZBK_wMs',
    appId: '1:133178926474:ios:28d9c66882cc3f9af35473',
    messagingSenderId: '133178926474',
    projectId: 'flutter-push-c35bc',
    storageBucket: 'flutter-push-c35bc.firebasestorage.app',
    iosBundleId: 'com.example.stecNotifica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjg7n866JYCG-jxCV8nxeodzdlXiXStKs',
    appId: '1:133178926474:web:ba9d45565736e351f35473',
    messagingSenderId: '133178926474',
    projectId: 'flutter-push-c35bc',
    authDomain: 'flutter-push-c35bc.firebaseapp.com',
    storageBucket: 'flutter-push-c35bc.firebasestorage.app',
    measurementId: 'G-9X3CFN4Z4B',
  );
}
